<a href="https://colab.research.google.com/github/TheClassicTechno/NumpyLinearAlgebraFunctions/blob/main/Linear_Algebra_Numpy_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra Numpy Functions

##by Julia Huang

##as I have just finished my college-level linear algebra course, in order to improve my knowledge of both linear algebra and the Python Numpy library, I have tested some of these numpy functions below with linear algebra tasks.

numpy link: https://numpy.org/doc/stable/reference/generated/numpy.linalg.eig.html

###Dot products

####This is the same as multiplying two matrices.

In [2]:
import numpy as np

In [3]:
a = [[1, 0], 
     [0, 1]]
     
b = [[4, 1], 
     [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

###Inner products 
####similar to dot product, this time its basically multiplying col 1 elements + multiplying col 2 elements, etc

Below, 1x0+2x1+3x0=2.



In [6]:
a = np.array([1,2,3])
b = np.array([0,1,0])
np.inner(a, b)

2

In [15]:
a = np.arange(2).reshape((1,1,2))
b = np.arange(6).reshape((3,2))
c = np.inner(a, b)

print(f"a matrix: {a}")
print(f"b matrix: {b}")
print(f"resulting matrix: {c}")
#here, 0 from a is multiplied to 0, 2, 4 in b and 1 from a is multipled to 1, 3, 5 in b.

a matrix: [[[0 1]]]
b matrix: [[0 1]
 [2 3]
 [4 5]]
resulting matrix: [[[1 3 5]]]


###matrix products

####similar to the above

In [11]:
a = np.array([[1, 0],
              [1, 1]])
b = np.array([[4, 1],
              [2, 2]])
np.matmul(a, b)

array([[4, 1],
       [6, 3]])

###trace of matrix
diagonal addition: 2+1=3

In [17]:
a=np.array([[2, 0],
              [1, 1]])
np.trace(a)

3

###return diagonal of matrix



In [18]:
x=np.array([[2, 0],
              [1, 1]])
np.diag(x)

array([2, 1])

###transpose

In [19]:
a = np.array([[1, 2], [3, 4]])
np.transpose(a)

array([[1, 3],
       [2, 4]])

###multiply scalar-ly or element-wise

In [21]:
x1 = np.arange(9.0).reshape((3, 3))
x2 = np.arange(3.0)
x3= np.multiply(x1, x2)

print(f"x1: {x1}")
print(f"x2: {x2}")
print(f"result: {x3}")

#here, first col of x2 multiple with 1st row of x1, and so on

#0 times 0,1,2 | 1 times 1,4,7 | 2 times 2,5,8

x1: [[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
x2: [0. 1. 2.]
result: [[ 0.  1.  4.]
 [ 0.  4. 10.]
 [ 0.  7. 16.]]


###find eigenvalues of matrix - outputted as an array of eigenvalues

In [24]:
from numpy import linalg as LA
A = np.array([[2, 1, -2], [1,0, 0], [0,1,0]])
LA.eigvals(A)


array([-1.,  2.,  1.])

###determinants

In [25]:
np.linalg.det(A)

-2.0

###rank

####basically means after doing rref(matrix), count num of leading 1s

In [27]:
from numpy.linalg import matrix_rank
matrix_rank(A)

3

###Solve the system of equations x0 + 2 * x1 = 1 and 3 * x0 + 5 * x1 = 2:

In [30]:
a = np.array([[1, 2], [3, 5]]) #coefficients of each var
b = np.array([1, 2]) #num to the right of equal sign
x = np.linalg.solve(a, b)
x

array([-1.,  1.])

In [31]:
#check that solution is correct
np.allclose(np.dot(a, x), b) #ax=b format

True

###calculate inverse of matrix

In [34]:
from numpy.linalg import inv
a = np.array([[1., 2.], [3., 4.]])
ainv = inv(a)
ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### square a matrix

In [6]:
arr2=([[4,3],[2,3],[1,2]])
np.square(arr2)

array([[16,  9],
       [ 4,  9],
       [ 1,  4]])

###matrix to a power - square matrices only

In [10]:
from numpy.linalg import matrix_power
arr2=([[4,3],[2,3]])
matrix_power(arr2, 3)

array([[130, 129],
       [ 86,  87]])

###convert bases

In [20]:
B1 = np.array([[1,1],[2,3]])

v1 = np.array([[3],[1]])
v2 = B1 @ v1 #basically multiply 2 matrices
v2



array([[4],
       [9]])

##einsums

basically a different way to write methods of linear algebra

Evaluates the Einstein summation convention on the operands. Using the Einstein summation convention, many common multi-dimensional, linear algebraic array operations can be represented in a simple fashion.

np.einsum('i,i', a, b) is equivalent to np.inner(a,b).

In [38]:
#np.einsum('ii', a) is equivalent to np.trace(a).
a = np.array([[1., 2.], [3., 4.]])
np.einsum('ii', a)

5.0

In [39]:
#transpose
np.einsum('ji', a)

array([[1., 3.],
       [2., 4.]])

In [43]:
#inner product (basically, 1st elem of 1st matrix*1st elem of 2nd matrix + 2nd el 1st mat*2nd el 2nd mat)
b = np.arange(5)
print(b)
np.einsum('i,i', b,b)

[0 1 2 3 4]


30

In [50]:
#matrix multiplication a*b
a = np.arange(9).reshape(3,3)
b = np.arange(3)
print(a)
print(b)
np.einsum('ij,j', a, b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]


array([ 5, 14, 23])

In [53]:
#output diagonal - in this case diagonal is 0 4 8
a = np.arange(9).reshape(3,3)
print(a)
np.einsum('ii->i', a)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([0, 4, 8])

##FFT
https://pythonnumericalmethods.berkeley.edu/notebooks/chapter24.04-FFT-in-Python.html


converts a signal from its original domain (often time or space) to a representation in the frequency domain 

convert a digital signal (x) with length (N) from the time domain into a signal in the frequency domain (X)

inverse FFT to obtain the original signal